// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Category    pgtype.Text        `json:"category"`
	Price       int64              `json:"price"`
	Status      pgtype.Text        `json:"status"`
	Tags        []string           `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ProductStock struct {
	ID         int32              `json:"id"`
	ProductID  uuid.UUID          `json:"product_id"`
	Location   pgtype.Text        `json:"location"`
	SoldAt     pgtype.Timestamptz `json:"sold_at"`
	ExpiryDate pgtype.Date        `json:"expiry_date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
