// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/products)
	ProductServiceCreateProduct(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ProductServiceCreateProduct operation middleware
func (siw *ServerInterfaceWrapper) ProductServiceCreateProduct(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ProductServiceCreateProduct(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/products", wrapper.ProductServiceCreateProduct)
}

type ProductServiceCreateProductRequestObject struct {
	Body *ProductServiceCreateProductJSONRequestBody
}

type ProductServiceCreateProductResponseObject interface {
	VisitProductServiceCreateProductResponse(w http.ResponseWriter) error
}

type ProductServiceCreateProduct200JSONResponse CreateProductResponse

func (response ProductServiceCreateProduct200JSONResponse) VisitProductServiceCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ProductServiceCreateProductdefaultJSONResponse struct {
	Body       Status
	StatusCode int
}

func (response ProductServiceCreateProductdefaultJSONResponse) VisitProductServiceCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/v1/products)
	ProductServiceCreateProduct(ctx context.Context, request ProductServiceCreateProductRequestObject) (ProductServiceCreateProductResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ProductServiceCreateProduct operation middleware
func (sh *strictHandler) ProductServiceCreateProduct(ctx *gin.Context) {
	var request ProductServiceCreateProductRequestObject

	var body ProductServiceCreateProductJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ProductServiceCreateProduct(ctx, request.(ProductServiceCreateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProductServiceCreateProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ProductServiceCreateProductResponseObject); ok {
		if err := validResponse.VisitProductServiceCreateProductResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xW34sbNxD+Vwa1Dw04a1+uL/XTuc5xmEJj7o5COQwZS7O7k2iljaT14R7+34uk9fnH",
	"miaFFPq2OyPNN/PNN5JehLRNaw2Z4MX0RXhZU4Ppc+4IAy2dVZ0M9/SlIx+iXZGXjtvA1oip6B3QkPdY",
	"EZTWgYw72VSA0ObtYiRaZ1tygSkFlxiosm4bv8O2JTEVPjg2ldiNThEu+A02dNHROpaXPT5g6BIyma4R",
	"0ycxmz8u/rgVI7H4vf9cjURpXYNBTPOq0Xmc3Ug4+tKxIxVDpDz2qKvX1Xb9iWSIqGcU+tYaT5c4zJ5/",
	"S+LePn0RPzoqxVT8MD60c9z3ctzjp/QHKd5ZW+mYYrDrrpyZ1BFUimNuqJdHgMF1dNYcMbcmIBsPaADd",
	"moNDtwVPjlHzX6ReS0JtTQXPHGpAuIlpQKgxQA63Jg+hJkh2W6bvYZBiwMBNruec0MdvCjVs7oCd5YHh",
	"76hfVv87WQ8qf3iNPKT2Y3Z+zBwrKtmQBwRtK5aogZyzDhqrSOcmswffccC1ztpWXJbkyIQo7cph00Sh",
	"k9mws6aJ4h0BG6k7Fe33tw+PMFsuosgU3C/n6aeARQrceVKw3sJTdb+cr36qQ2j9dDyuONTdupC2GVeu",
	"lW8KuEVZH1Lf61LuBRxqRwQtkyQfdaMw4LQvRVpFo31ZeeMoJZNNigKy9gX8aTuQaKBko8B2ARrrCHAd",
	"P0PN/oSZuL+2zxAsPFv3Oc8GB2CTNPs0Wy7gPXmuDNx1rOhQm9S2U0WVJjdViC37sUprxwnCvxnOSizi",
	"cj+zivoqn2uWNfjadlrBmuJgR9XABnWXBuqpB3atLOZW0WpgiNivkmMTrt8dNMcmUEUuj0mibZjTDDT7",
	"ELF6sn2WkUTntomcM97hsSZHUQ0I0jaNNeDpOEBSqk/aS0IKNuom5smBGv+1E3R4SB5GBp3D9N9DXSpH",
	"0YZ07MXbEmWS+qmUzjlnA7em0uzrAmZmG3O9vPVoj7ayP+KisHwcrr2SjvqT5V/0zK3+wQUlk1YjsO4o",
	"9DrTLzWTCd90hkYTm9JmBZqA+TSlBllH9kKNBj3jLz9fTW6qaI2KFvvTUNyRNfW2+wyLZnC0ig8toYlz",
	"srkGZWUXj47U5Nu3c9s05CS9nS0XMU8OOoYbODbkfA42KSbFVcSwLRlsWUzFdTEpruMgYaiTSOKkjTdX",
	"4/7mzbewvfQuWn54eITB8hTcYVyzUHFVdjyQ27Ckk+eCyG8N8uFXq7Z7+sgkLGxbzTLFGX/y+ZrJYv2a",
	"lC++6nanL5t40SdDfpakKt9NJv9VDv2zKCVx1t/fcs9L7HT4bvD91XYB731G6mfMHTIbiYCVj/fracfE",
	"anfkfNmL9mzRbrX7OwAA//+eRuyfaAsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
