version: "2"
sql:
- engine: "postgresql"
  queries: "./sqlc/queries.sql"
  schema: "./migrations"
  gen:
    go:
      package: "sqlc"
      out: "./sqlc"
      sql_package: "pgx/v5"
      emit_json_tags: true
      emit_prepared_queries: true
      emit_exact_table_names: false
      emit_interface: true
      emit_empty_slices: true
      overrides:
      - db_type: "uuid"
        go_type: "github.com/google/uuid.UUID"
      - db_type: "text"
        go_type: "string"
      - db_type: "timestamp"
        go_type: "time.Time"
